// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4pFDf-P8KxCj4bOWcEdQ9BUwfIa1CHs',
    appId: '1:997778724573:web:ed934164dcae1e73a0ed34',
    messagingSenderId: '997778724573',
    projectId: 'fiance-9e528',
    authDomain: 'fiance-9e528.firebaseapp.com',
    storageBucket: 'fiance-9e528.appspot.com',
    measurementId: 'G-ECZXEDCSX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjjMMtl8dsVW5xqpnwpmyDHP6O-LQ6wM',
    appId: '1:997778724573:android:547921745d1a39f9a0ed34',
    messagingSenderId: '997778724573',
    projectId: 'fiance-9e528',
    storageBucket: 'fiance-9e528.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYg2opjNxSCqwUDbGUh8mjwhUbeQJ8Bzc',
    appId: '1:997778724573:ios:0b8ea1fcffcaab56a0ed34',
    messagingSenderId: '997778724573',
    projectId: 'fiance-9e528',
    storageBucket: 'fiance-9e528.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYg2opjNxSCqwUDbGUh8mjwhUbeQJ8Bzc',
    appId: '1:997778724573:ios:0b8ea1fcffcaab56a0ed34',
    messagingSenderId: '997778724573',
    projectId: 'fiance-9e528',
    storageBucket: 'fiance-9e528.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG4pFDf-P8KxCj4bOWcEdQ9BUwfIa1CHs',
    appId: '1:997778724573:web:3e316807d3cd750fa0ed34',
    messagingSenderId: '997778724573',
    projectId: 'fiance-9e528',
    authDomain: 'fiance-9e528.firebaseapp.com',
    storageBucket: 'fiance-9e528.appspot.com',
    measurementId: 'G-G8FGHXZ40J',
  );
}
